---
  percona_cluster_bind_address: "::"
  percona_cluster_name: "testcluster"
  percona_cluster_expire_log_days: 8
  percona_cluster_max_allowed_packet: "16M"
  percona_cluster_sst_user: "testclusteruser"
  percona_cluster_sst_password: "testclusterpassword"
  percona_cluster_root_password: "changeme"
  percona_cluster_version: "5.7"
