---

  - name: Add percona repo
    become: yes
    apt:
      deb: "https://repo.percona.com/apt/percona-release_0.1-4.xenial_all.deb"

  - name: Update apt
    become: yes
    apt:  update_cache=yes

  - name: Install Python package manager on Ubuntu 16.04
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - python3-dev
      - libmysqlclient-dev
      - python3-pip

  - name: Install the Python MySQLB module
    pip:
      name: "{{ item }}"
    with_items:
      - pip
      - mysqlclient

  - name: Sets root password
    debconf:
      name: "percona-xtradb-cluster-{{ percona_cluster_version|replace('.','') }}"
      question: "{{ item }}"
      value: "{{ percona_cluster_root_password }}"
      vtype: 'password'
    changed_when: false
    with_items:
      - 'root_password'
      - 'root_password_again'

  - name: Sets root password again
    debconf:
      name: "percona-xtradb-cluster-server-{{ percona_cluster_version }}"
      question: "percona-xtradb-cluster-server/{{ item }}"
      value: "{{ percona_cluster_root_password }}"
      vtype: 'password'
    changed_when: false
    with_items:
      - 'root_password'
      - 'root_password_again'

  - name: Easy access for Root user
    template:
      src: 'root_my.cnf.j2'
      dest: '/root/.my.cnf'

  - name: Installs percona-server
    apt:
      pkg: "percona-xtradb-cluster-{{ percona_cluster_version|replace('.','') }}"
      state: present

  - name: Configure MySQL
    template:
      src: "my.cnf.j2"
      dest: '/etc/mysql/my.cnf'

  - name: Stop all mysql servers
    service:
      name: mysql
      state: stopped

  - name: Bootstrap percona cluster non-primary servers
    command: service mysql bootstrap-pxc
    when: "'database-master' in group_names"

  - name: Add replication user
    mysql_user:
      priv: "*.*:GRANT,RELOAD,LOCK TABLES,PROCESS,REPLICATION CLIENT"
      user: "{{ percona_cluster_sst_user }}"
      password: "{{ percona_cluster_sst_password }}"
      host: localhost
    when: "'database-master' in group_names"

  - name: Add proxysql monitoring user
    mysql_user:
      priv: "*.*:usage"
      user: "{{ proxysql_monitor_username }}"
      password: "{{ proxysql_monitor_password }}"
      host: '%'
    when: "'database-master' in group_names"

  - name: Stop all mysql servers
    service:
      name: mysql
      state: stopped

  - name: Bootstrap percona cluster non-primary servers
    command: service mysql bootstrap-pxc
    when: "'database-master' in group_names"

  - name: Restart percona cluster
    service:
      name: mysql
      state: restarted
    when: "'database-master' not in group_names"

  - name: Restart 'master'
    service:
      name: mysql
      state: restarted
    when: "'database-master' in group_names"
