---

  init_packages:
  - build-essential
  - python-software-properties
  - software-properties-common
  - vim
  - curl
  - wget
  - mcrypt
  - git-core
  - git
  - zip
  - fail2ban
  - monit
  - debconf-utils

  ansible_python_interpreter: "/usr/bin/python3"
